from PIL import Image, ImageOps
import base64
from io import BytesIO

speed = 4000 # Velocity (mm/s)
accel = 1000 # Acceleration (mm/s^2)
tipsize = 0.3 # Size (mm) of pen tip
origin = (0,0) # Origin point of drawing on paper

# Shrinks pixels by the size of the pen tip to try
# and prevent the pen from slightly overlapping other pixels
# Only applies when the pixel size is larger than the tip size
# 1.0 = pen tip entirely detached from adjacent pixels
# 0.0 = pen tip midpoint touching adjacent pixels
# -1.0 = pen tip completely overlapping adjacent pixels
overlap = 0.0

img = Image.open("dithered-image.png")
img = ImageOps.flip(img)
img = img.convert('RGB')
print(f"Image size: {img.size}")
papersize = input("Enter X*Y paper size: ")
paperX = int(papersize.split('*')[0])
paperY = int(papersize.split('*')[1])

margin = input("Enter margin size: ")
margin = int(margin)

minsize = min(paperX, paperY) - (margin*2)

pixelSize = round(minsize / min(img.size[0], img.size[1]),2)

print(f"Pixel size: {pixelSize}mm^2")

colours = set()
for i in range(img.size[0]):
    for j in range(img.size[1]):
        pixel = img.getpixel((i, j))
        colours.add(pixel)

print('Colour count = ', len(colours))

input("Generate gcode? (press enter to continue)")
print()
pixelSizeOffset = tipsize * overlap if tipsize < pixelSize else 0

for colour in colours:
    open(f"gcode_{colour[0]}_{colour[1]}_{colour[2]}.gcode", 'w').close()
    file = open(f"gcode_{colour[0]}_{colour[1]}_{colour[2]}.gcode", "a")

    file.write(f"; generated by PrusaSlicer 2.9.2 on 2025-12-07 at 17:04:26 UTC\n")

    file.write(f"; external perimeters extrusion width = 0.45mm\n")
    file.write(f"; perimeters extrusion width = 0.45mm\n")
    file.write(f"; infill extrusion width = 0.45mm\n")
    file.write(f"; solid infill extrusion width = 0.45mm\n")
    file.write(f"; top infill extrusion width = 0.40mm\n")
    file.write(f"; support material extrusion width = 0.40mm\n")
    
    file.write(f";TYPE:Custom\n")
    file.write(f"M117 ; idk why this is necessary but whatever\n")
    file.write(f"START_PRINT\n")
    file.write(f"G21 ; Set units to millimeters\n")
    file.write(f"G90 ; Use absolute positioning\n")
    file.write(f"M82 ; Absolute positioning for extruder (maybe necessary?)\n")
    file.write(f"G92 E0 ; Reset extruder\n")
    file.write(f"M107 ; Fan off\n")
    file.write(f"M204 S{accel} ; Set acceleration\n")
    file.write(f"G1 Z5 F{speed} ; Lift pen\n")
    file.write(f"G1 X0 Y0 F{speed} ; Move to origin\n")
    file.write(f"G1 E1 ; Necessary extrude to make file valid in the eyes of prusaslicer\n")

    if tipsize < pixelSize or pixelSizeOffset != 0:
        for i in range(img.size[0]):
            for j in range(img.size[1]):
                pixel = img.getpixel((i, j))
                if pixel == colour:
                    #pixelSizeOffset
                    pixelDraw = round((pixelSize)/2,2)

                    x = round((i*pixelSize) + margin + origin[0], 2)
                    y = round((j*pixelSize) + margin + origin[1], 2)

                    file.write(f"G1 X{(x-pixelDraw)+pixelSizeOffset} Y{(y-pixelDraw)+pixelSizeOffset} F{speed}\n")
                    file.write(f"G1 Z0 F{speed}\n")
                    file.write(f"G1 X{(x+pixelDraw)-pixelSizeOffset} Y{(y-pixelDraw)+pixelSizeOffset} F{speed}\n")
                    file.write(f"G1 X{(x+pixelDraw)-pixelSizeOffset} Y{(y+pixelDraw)-pixelSizeOffset} F{speed}\n")
                    file.write(f"G1 X{(x-pixelDraw)+pixelSizeOffset} Y{(y+pixelDraw)-pixelSizeOffset} F{speed}\n")
                    file.write(f"G1 X{(x-pixelDraw)+pixelSizeOffset} Y{(y-pixelDraw)+pixelSizeOffset} F{speed}\n")
                    file.write(f"G1 Z5 F{speed}\n")
    else:
        for i in range(img.size[0]):
            for j in range(img.size[1]):
                pixel = img.getpixel((i, j))
                if pixel == colour:
                    x = round(i / pixelSize, 2)
                    y = round(j / pixelSize, 2)
                    file.write(f"G1 X{x} Y{y} F{speed}\n")
                    file.write(f"G1 Z0 F{speed}\n")
                    file.write(f"G1 Z5 F{speed}\n")

    file.write("G1 Z5 F5000 ; Lift pen\n")
    file.write(f"M84 ; Disable motors\n")
    #file.write(f"; prusaslicer_config = end\n")